import sys
from functools import cmp_to_key
from urllib.parse import quote

import apt
from launchpadlib import uris
from launchpadlib.credentials import AccessToken, Credentials
from launchpadlib.launchpad import Launchpad
from lazr.restfulclient.errors import HTTPError

from errortracker import config

if (
    not hasattr(config, "lp_oauth_token")
    or not hasattr(config, "lp_oauth_secret")
    or config.lp_oauth_token is None
    or config.lp_oauth_secret is None
):
    raise ImportError("You must set lp_oauth_token and lp_oauth_secret in local_config")

if config.lp_use_staging == "True":
    _service_root = uris.QASTAGING_SERVICE_ROOT
    _bug_web_url = "https://qastaging.launchpad.net/bugs/"
else:
    _service_root = uris.LPNET_SERVICE_ROOT
    _bug_web_url = "https://bugs.launchpad.net/bugs/"

# launchpadlib uses "testing" as the OAuth consumer, matching the credentials
# previously generated by hand.
_OAUTH_CONSUMER = "testing"

# Lazily-instantiated, module-level launchpadlib handles. They are created on
# first use rather than at import time to avoid making network requests when
# the module is merely imported.
_launchpad = None
_ubuntu_distro = None
_primary_archive_obj = None


def _get_launchpad():
    global _launchpad
    if _launchpad is None:
        access_token = AccessToken(key=config.lp_oauth_token, secret=config.lp_oauth_secret)
        credentials = Credentials(
            consumer_name=_OAUTH_CONSUMER,
            access_token=access_token,
        )
        _launchpad = Launchpad(
            credentials,
            None,
            None,
            service_root=_service_root,
            cache=config.http_cache_dir,
            version="devel",
        )
    return _launchpad


def _ubuntu():
    global _ubuntu_distro
    if _ubuntu_distro is None:
        _ubuntu_distro = _get_launchpad().distributions["ubuntu"]
    return _ubuntu_distro


def _primary_archive():
    global _primary_archive_obj
    if _primary_archive_obj is None:
        _primary_archive_obj = _ubuntu().main_archive
    return _primary_archive_obj


def _get_series(codename):
    """Return the distro series for a codename, or None if it does not exist."""
    if not codename:
        return None
    try:
        return _ubuntu().getSeries(name_or_version=codename)
    except (KeyError, HTTPError):
        return None


def _get_i386_distro_arch_series(codename):
    """Return the i386 DistroArchSeries for a codename, or None."""
    series = _get_series(codename)
    if series is None:
        return None
    try:
        return series.getDistroArchSeries(archtag="i386")
    except (KeyError, HTTPError):
        return None


# Bug and package lookup.


def get_all_codenames():
    return [series.name for series in _ubuntu().series]


def get_codename_for_version(version):
    release_codenames = {
        "12.04": "precise",
        "12.10": "quantal",
        "13.04": "raring",
        "13.10": "saucy",
        "14.04": "trusty",
        "14.10": "utopic",
        "15.04": "vivid",
        "15.10": "wily",
        "16.04": "xenial",
        "16.10": "yakkety",
        "17.04": "zesty",
        "17.10": "artful",
        "18.04": "bionic",
        "18.10": "cosmic",
        "19.04": "disco",
        "19.10": "eoan",
        "20.04": "focal",
        "20.10": "groovy",
        "21.04": "hirsute",
        "21.10": "impish",
        "22.04": "jammy",
        "22.10": "kinetic",
        "23.04": "lunar",
        "23.10": "mantic",
        "24.04": "noble",
        "24.10": "oracular",
    }
    if not version:
        return None
    if version in list(release_codenames.values()):
        return version
    elif version.startswith("Ubuntu "):
        version = version.replace("Ubuntu ", "")
    if version in release_codenames:
        return release_codenames[version]
    elif version == "Ubuntu RTM 14.09":
        return "14.09"
    else:
        for series in _ubuntu().series:
            if series.version == version:
                return series.name
    return None


def get_devel_series_codename():
    from datetime import datetime

    import distro_info

    di = distro_info.UbuntuDistroInfo()
    today = datetime.today().date()
    try:
        codename = di.devel(today)
    # this can happen on release and before
    # distro-info-data is SRU'ed
    except distro_info.DistroDataOutdated:
        codename = di.stable()
    return codename


def get_version_for_codename(codename):
    for series in _ubuntu().series:
        if series.name == codename:
            return series.version
    return None


def get_versions_for_binary(binary_package, ubuntu_version):
    if not ubuntu_version:
        codename = get_devel_series_codename()
    else:
        codename = get_codename_for_version(ubuntu_version)
    if not codename:
        return []
    if is_source_package(binary_package):
        series = _get_series(codename)
        if series is None:
            return ""
        sources = _ubuntu().main_archive.getPublishedSources(
            exact_match=True,
            status="Published",
            source_name=binary_package,
            distro_series=series,
        )
        # use the first one, since they are unordered
        try:
            source = sources[0]
        except IndexError:
            return ""
        binaries = source.getPublishedBinaries()
        try:
            # use the first binary package since all versions should be the
            # same
            binary_package = binaries[0].binary_package_name
        except IndexError:
            return ""
    # i386 and amd64 versions should be the same, hopefully.
    das = _get_i386_distro_arch_series(codename)
    if das is None:
        return []
    binaries = _primary_archive().getPublishedBinaries(
        binary_name=binary_package,
        exact_match=True,
        distro_arch_series=das,
    )
    results = set(
        binary.binary_package_version
        for binary in binaries
        if binary.binary_package_version
    )
    return sorted(results, key=cmp_to_key(apt.apt_pkg.version_compare))


def get_release_for_binary(binary_package, version):
    binaries = _primary_archive().getPublishedBinaries(
        binary_name=binary_package,
        version=version,
        exact_match=True,
        status="Published",
        order_by_date=True,
    )
    results = set(
        get_version_for_codename(binary.display_name.split(" ")[3]) for binary in binaries
    )
    return results


def binaries_are_most_recent(specific_packages, release=None):
    """For each (package, version) tuple supplied, determine if that is the
    most recent version of the binary package.

    This method lets us cache repeated lookups of the most recent version of
    the same binary package."""

    _cache = {}
    result = []
    for package, version in specific_packages:
        if not package or not version:
            result.append(True)
            continue

        if package in _cache:
            latest_version = _cache[package]
        else:
            latest_version = _get_most_recent_binary_version(package, release)
            # We cache this even if _get_most_recent_binary_version returns
            # None, as packages like Skype will always return None and we
            # shouldn't keep asking.
            _cache[package] = latest_version

        if latest_version:
            r = apt.apt_pkg.version_compare(version, latest_version) != -1
            result.append(r)
        else:
            result.append(True)
    return result


def _get_most_recent_binary_version(package, release):
    kwargs = {
        "binary_name": package,
        "exact_match": True,
        "status": "Published",
        "order_by_date": True,
    }
    if release:
        # TODO cache this by pushing it into the above function and instead
        # passing the distro_arch_series url.
        codename = get_codename_for_version(release.split()[1])
        das = _get_i386_distro_arch_series(codename)
        if das is not None:
            kwargs["distro_arch_series"] = das
    try:
        return _primary_archive().getPublishedBinaries(**kwargs)[0].binary_package_version
    except (KeyError, IndexError):
        return ""


def pocket_for_binaries(specific_packages):
    """For each (package, version, release) tuple supplied, determine the
    pocket in which the package version appears.

    This method lets us cache repeated lookups of the pocket for the same
    binary package."""

    _cache = {}
    result = []
    for package, version, release in specific_packages:
        if not package or not version or not release:
            result.append("Not Found")
            continue

        if (package, version, release) in _cache:
            pocket = _cache[package, version, release]
        else:
            pocket = _get_pocket_for_binary_version(package, version, release)
            # We cache this even if _get_pocket_for_binary_version returns
            # None, as packages like Skype will always return None and we
            # shouldn't keep asking.
            _cache[package, version, release] = "%s" % (pocket)
        result.append(pocket)
    return result


def _get_pocket_for_binary_version(package, version, release):
    # the package version may be Superseded or Obsolete, so do not restrict by
    # status here.
    kwargs = {
        "binary_name": package,
        "version": version,
        "exact_match": True,
        "order_by_date": True,
    }
    # TODO cache this by pushing it into the above function and instead
    # passing the distro_arch_series url.
    codename = get_codename_for_version(release.split()[-1])
    das = _get_i386_distro_arch_series(codename)
    if das is not None:
        kwargs["distro_arch_series"] = das
    try:
        pocket = _primary_archive().getPublishedBinaries(**kwargs)[0].pocket
        return "%s" % pocket
    except (KeyError, IndexError):
        return ""


def binary_is_most_recent(package, version):
    # FIXME we need to factor in the release, otherwise this is often going to
    # look like the issue has disappeared when filtering the most common
    # problems view to a since-passed release.
    latest_version = _get_most_recent_binary_version(package, None)
    if not latest_version:
        return True
    # If the version we've been provided is older than the latest version,
    # return False; it's not the newest. We will then assume that because
    # we haven't seen it in the new version it may be fixed.
    return apt.apt_pkg.version_compare(version, latest_version) != -1


def bug_is_fixed(bug, release=None):
    if release:
        release = release.split()[1]
    codename = get_codename_for_version(release)
    if codename:
        codename_task = " (ubuntu %s)" % codename
    else:
        codename_task = ""

    try:
        bug_obj = _get_launchpad().bugs[int(bug)]
        entries = list(bug_obj.bug_tasks)
    except (ValueError, KeyError, HTTPError):
        # We will presume that this is a private bug.
        return None

    if len(entries) == 0:
        # We will presume that this is a private bug.
        return None

    try:
        for entry in entries:
            name = entry.bug_target_name
            if release and codename and name.lower().endswith(codename_task):
                if not entry.is_complete:
                    return False
                elif entry.is_complete:
                    return True

        # Lets iterate again and see if we can find the Ubuntu task.
        for entry in entries:
            name = entry.bug_target_name
            # Do not look at upstream bug tasks.
            if name.endswith(" (Ubuntu)"):
                # We also consider bugs that are Invalid as complete. I am not
                # entirely sure that is correct in this context.
                if not entry.is_complete:
                    # As the bug itself may be in a library package bug task,
                    # it is not sufficient to return True at the first complete
                    # bug task.
                    return False
        return True
    except (ValueError, KeyError):
        return False


def bug_get_master_id(bug):
    """Return master bug (of which given bug is a duplicate)

    Return None if bug is not a duplicate.
    """
    try:
        bug_obj = _get_launchpad().bugs[int(bug)]
        master = bug_obj.duplicate_of
        if master:
            return str(master.id)
    except (ValueError, KeyError, HTTPError, AttributeError):
        pass
    return None


def is_source_package(package_name):
    dev_series = get_devel_series_codename()
    series = _get_series(dev_series)
    if series is None:
        return False
    try:
        source_package = series.getSourcePackage(name=package_name)
    except (KeyError, HTTPError):
        return False
    return source_package is not None


def get_binaries_in_source_package(package_name, release=None):
    # FIXME: in the event that a package does not exist in the devel release
    # an empty set will be returned and binary packages from previous releases
    # will be missed e.g. synaptiks in trusty
    if not release:
        dev_series = get_devel_series_codename()
    else:
        dev_series = get_codename_for_version(release)
    series = _get_series(dev_series)
    if series is None:
        return ""
    sources = _ubuntu().main_archive.getPublishedSources(
        exact_match=True,
        status="Published",
        source_name=package_name,
        distro_series=series,
    )
    # just use the first one, since they are unordered
    try:
        source = sources[0]
    except IndexError:
        return ""
    pbs = set()
    for binary in source.getPublishedBinaries():
        pbs.add(binary.binary_package_name)
    return pbs


def get_subscribed_packages(user):
    """return binary packages to which a user is subscribed"""
    person = _get_launchpad().people[user]
    src_pkgs = [src_pkg.name for src_pkg in person.getBugSubscriberPackages()]
    bin_pkgs = []
    for src_pkg in src_pkgs:
        bin_pkgs.extend(list(get_binaries_in_source_package(src_pkg)))
    return bin_pkgs


def get_packages_in_packageset_name(release, name):
    if not release:
        series = get_devel_series_codename()
    else:
        series = get_codename_for_version(release)
    series_obj = _get_series(series)
    if series_obj is None:
        return ""
    try:
        packageset = _get_launchpad().packagesets.getByName(
            name=name, distroseries=series_obj
        )
    except (KeyError, HTTPError):
        return ""
    return list(packageset.getSourcesIncluded())


def is_valid_source_version(src_package, version):
    sources = _primary_archive().getPublishedSources(
        source_name=src_package,
        version=version,
        exact_match=True,
    )
    return len(sources) >= 1


def get_pocket_for_source_version(src_package, version, release):
    # hack for packages from RTM
    if release == "Ubuntu RTM 14.09":
        distro = _get_launchpad().distributions["ubuntu-rtm"]
    else:
        distro = _ubuntu()
    series_name = get_codename_for_version(release.split()[-1])
    kwargs = {
        "source_name": src_package,
        "version": version,
        "exact_match": True,
        "order_by_date": True,
    }
    try:
        series = distro.getSeries(name_or_version=series_name)
    except (KeyError, HTTPError):
        series = None
    if series is not None:
        kwargs["distro_series"] = series
    try:
        pocket = distro.main_archive.getPublishedSources(**kwargs)[0].pocket
        return "%s" % pocket
    except (KeyError, IndexError):
        return "?"


# Bug creation.


def create_bug(signature, source="", releases=[], hashed=None, lastseen=""):
    """Returns a tuple of (bug number, url)"""

    # temporary solution to LP: #1322325 by creating short titles
    if signature.startswith("Traceback (most recent call last"):
        lines = signature.splitlines()
        title = "%s crashed with %s" % (source, lines[-1])
    else:
        title = "%s" % signature
    details = (
        "details, including versions of packages affected, "
        "stacktrace or traceback, and individual crash reports"
    )

    if not hashed:
        href = "https://errors.ubuntu.com/bucket/?id=%s" % quote(signature)
    else:
        href = "https://errors.ubuntu.com/problem/%s" % hashed

    if source and lastseen:
        description = (
            "The Ubuntu Error Tracker has been receiving reports "
            "about a problem regarding %s.  This problem was "
            "most recently seen with package version %s, the "
            "problem page at %s contains more %s." % (source, lastseen, href, details)
        )
    else:
        description = (
            "The Ubuntu Error Tracker has been receiving reports "
            "about a problem regarding %s.  The problem page at "
            "%s contains more %s." % (source, href, details)
        )
    description += (
        "\nIf you do not have access to the Ubuntu Error Tracker "
        "and are a software developer, you can request it at "
        "http://forms.canonical.com/reports/."
    )

    release_codenames = []
    for release in releases:
        # release_codenames need to be strings not unicode
        codename = get_codename_for_version(release)
        if codename:
            release_codenames.append("%s" % str(codename))
        else:
            # can't use capital letters or spaces in a tag e.g. 'RTM 14.09'
            release = release.lower()
            release_codenames.append("%s" % str(release).replace(" ", "-"))
    tags = release_codenames

    lp = _get_launchpad()
    if source:
        target = _ubuntu().getSourcePackage(name=source)
    else:
        target = _ubuntu()

    # TODO Record the source packages and Ubuntu releases this crash has been
    # seen in, so we can add tasks for each relevant release.
    try:
        bug = lp.bugs.createBug(
            description=description,
            target=target,
            title=title,
            tags=tags,
        )
    except HTTPError as e:
        print("Could not create bug:", str(e), file=sys.stderr)
        return (None, None)

    number = str(bug.id)
    return (number, _bug_web_url + number)


def subscribe_user(bug, user):
    lp = _get_launchpad()
    try:
        bug_obj = lp.bugs[int(bug)]
        person = lp.people[user]
        bug_obj.subscribe(person=person, level="Discussion")
    except (ValueError, KeyError, HTTPError) as e:
        msg = "Could not subscribe %s to bug %s:" % (user, bug)
        print(msg, str(e), file=sys.stderr)
